### ISSUE TITLE
Migrate to RevenueCat's `v2` API

### ISSUE THREAD

**Issue by bnussman** [bnussman/beep#112]
## Description

Migrate from RevenueCat's `v1` API to their `v2` API

## Todo
- [ ] Create new API key
- [ ] Update Github with new secrets
- [ ] Update codebase to use `https://api.revenuecat.com/v2/projects/{project_id}/customers/{customer_id}/purchases` rather than `https://api.revenuecat.com/v1/subscribers/{customer_id}` ([docs](https://www.revenuecat.com/docs/api-v2#tag/Customer/operation/list-subscriptions))
- [ ] Test thoroughly

## Existing Code 
https://github.com/bnussman/beep/blob/4217296cbbecd0ae6de208988f516e074eaac9e1/api/src/utils/payments.ts#L28-L81
